version: "3.8"

services:
  web:
    image: ${DOCKERHUB_USER}/fastapi-app:${IMAGE_TAG}
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - webnet

networks:
  webnet:
    driver: overlay
